### ISSUE TITLE
Ask

### ISSUE THREAD

**Issue by HAfsari** [RonnyWeiss/Apex-SweetAlert-Confirm#1]
Dear... 
 How to submit without Confirmation reference not item value.  or Hide Text item.

**Comment by RonnyWeiss** [comment]
Hello

Can you explain it to me? Correct my when I'm wrog but you want to confirm with not input, you just want to have the ui of my plugin?

kr

Ronny

**Comment by RonnyWeiss** [comment]
I feature request is still needed please reopen
