### ISSUE TITLE
How to use input type checkbox?

### ISSUE THREAD

**Issue by aragorniiit** [RonnyWeiss/Apex-SweetAlert-Confirm#2]
Hi Ronny

How to use input type checkbox? I gave P9_COMPARE value as Y and 1. Either one did not validate successfully.

Also How to pass parameters to the function as you mentioned in the help text?

Thanks
Kishore

**Comment by RonnyWeiss** [comment]
Does it work when you enter 1?

**Comment by RonnyWeiss** [comment]
Because the plug-in compares the value and not the display value so maybe you can try to set it the same

**Comment by RonnyWeiss** [comment]
No reacton after weeks.... Will Close the Issues
